name: Climatology files for ROMS
channels:
  - pip
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - partd
  - bokeh
  - dask
  - holoview
  - netCDF4
  - xarray 
  - s3fs
  - holoviews
